---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: tg-schedule
  namespace: day-to-remember

spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: day-to-remember
      component: tg-schedule
  template:
    metadata:
      labels:
        app: day-to-remember
        component: tg-schedule
    spec:
      containers:
        - name: main

          image: agrrh/day-to-remember:dev-20260201-182621
          command: ["uv"]
          args: ["run", "tg_schedule.py"]

          env:
            - name: TZ
              value: Europe/Moscow

            - name: TG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: config
                  key: TG_TOKEN

            - name: GRIST_URL
              valueFrom:
                secretKeyRef:
                  name: config
                  key: GRIST_URL
            - name: GRIST_TOKEN
              valueFrom:
                secretKeyRef:
                  name: config
                  key: GRIST_TOKEN
            - name: GRIST_DOC_ID
              valueFrom:
                secretKeyRef:
                  name: config
                  key: GRIST_DOC_ID
